# l10n -> localization
synthetic-package: false
arb-dir: lib/presentation/core/l10n
template-arb-file: app_ar.arb
output-localization-file: app_localizations.dart
output-dir: lib/presentation/core/l10n