// Mocks generated by Mockito 5.4.6 from annotations
// in islamy_app/test/presentation/modules/mainScreen/layouts/quran_layout/quran_layout_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i7;

import 'package:flutter/material.dart' as _i3;
import 'package:islamy_app/presentation/core/providers/locale_provider.dart'
    as _i6;
import 'package:islamy_app/presentation/modules/mainScreen/provider/main_screen_provider.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:shared_preferences/shared_preferences.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSharedPreferences_0 extends _i1.SmartFake
    implements _i2.SharedPreferences {
  _FakeSharedPreferences_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTextEditingController_1 extends _i1.SmartFake
    implements _i3.TextEditingController {
  _FakeTextEditingController_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NavigatorObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigatorObserver extends _i1.Mock implements _i3.NavigatorObserver {
  @override
  void didPush(
    _i3.Route<dynamic>? route,
    _i3.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didPush,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didPop(
    _i3.Route<dynamic>? route,
    _i3.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didPop,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didRemove(
    _i3.Route<dynamic>? route,
    _i3.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didRemove,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didReplace({
    _i3.Route<dynamic>? newRoute,
    _i3.Route<dynamic>? oldRoute,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #didReplace,
          [],
          {
            #newRoute: newRoute,
            #oldRoute: oldRoute,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeTop(
    _i3.Route<dynamic>? topRoute,
    _i3.Route<dynamic>? previousTopRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didChangeTop,
          [
            topRoute,
            previousTopRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didStartUserGesture(
    _i3.Route<dynamic>? route,
    _i3.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didStartUserGesture,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didStopUserGesture() => super.noSuchMethod(
        Invocation.method(
          #didStopUserGesture,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MainScreenProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockMainScreenProvider extends _i1.Mock
    implements _i4.MainScreenProvider {
  @override
  _i2.SharedPreferences get sharedPreferences => (super.noSuchMethod(
        Invocation.getter(#sharedPreferences),
        returnValue: _FakeSharedPreferences_0(
          this,
          Invocation.getter(#sharedPreferences),
        ),
        returnValueForMissingStub: _FakeSharedPreferences_0(
          this,
          Invocation.getter(#sharedPreferences),
        ),
      ) as _i2.SharedPreferences);

  @override
  int get bottomBarCurrentIndex => (super.noSuchMethod(
        Invocation.getter(#bottomBarCurrentIndex),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  bool get isBottomBarEnabled => (super.noSuchMethod(
        Invocation.getter(#isBottomBarEnabled),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String get markedHadeethIndex => (super.noSuchMethod(
        Invocation.getter(#markedHadeethIndex),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#markedHadeethIndex),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.getter(#markedHadeethIndex),
        ),
      ) as String);

  @override
  _i3.TextEditingController get searchFieldController => (super.noSuchMethod(
        Invocation.getter(#searchFieldController),
        returnValue: _FakeTextEditingController_1(
          this,
          Invocation.getter(#searchFieldController),
        ),
        returnValueForMissingStub: _FakeTextEditingController_1(
          this,
          Invocation.getter(#searchFieldController),
        ),
      ) as _i3.TextEditingController);

  @override
  String get markedSurahIndex => (super.noSuchMethod(
        Invocation.getter(#markedSurahIndex),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#markedSurahIndex),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.getter(#markedSurahIndex),
        ),
      ) as String);

  @override
  set bottomBarCurrentIndex(int? _bottomBarCurrentIndex) => super.noSuchMethod(
        Invocation.setter(
          #bottomBarCurrentIndex,
          _bottomBarCurrentIndex,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isBottomBarEnabled(bool? _isBottomBarEnabled) => super.noSuchMethod(
        Invocation.setter(
          #isBottomBarEnabled,
          _isBottomBarEnabled,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set markedHadeethIndex(String? _markedHadeethIndex) => super.noSuchMethod(
        Invocation.setter(
          #markedHadeethIndex,
          _markedHadeethIndex,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set markedSurahIndex(String? _markedSurahIndex) => super.noSuchMethod(
        Invocation.setter(
          #markedSurahIndex,
          _markedSurahIndex,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void getLocaleProvider(_i6.LocaleProvider? localeProvider) =>
      super.noSuchMethod(
        Invocation.method(
          #getLocaleProvider,
          [localeProvider],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void getMainScreenData() => super.noSuchMethod(
        Invocation.method(
          #getMainScreenData,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void saveBarEnablement(bool? newValue) => super.noSuchMethod(
        Invocation.method(
          #saveBarEnablement,
          [newValue],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void changeBarEnablement(bool? newValue) => super.noSuchMethod(
        Invocation.method(
          #changeBarEnablement,
          [newValue],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void changeBarIndex(int? newIndex) => super.noSuchMethod(
        Invocation.method(
          #changeBarIndex,
          [newIndex],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void changeMarkedHadeeth(String? hadeethIndex) => super.noSuchMethod(
        Invocation.method(
          #changeMarkedHadeeth,
          [hadeethIndex],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showAlertAboutHadeethMarking(String? hadeethToMarkIndex) =>
      super.noSuchMethod(
        Invocation.method(
          #showAlertAboutHadeethMarking,
          [hadeethToMarkIndex],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<String> getSurasListEnglishOrArabic() => (super.noSuchMethod(
        Invocation.method(
          #getSurasListEnglishOrArabic,
          [],
        ),
        returnValue: <String>[],
        returnValueForMissingStub: <String>[],
      ) as List<String>);

  @override
  void changeMarkedSurah(String? index) => super.noSuchMethod(
        Invocation.method(
          #changeMarkedSurah,
          [index],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showAlertAboutSurasMarking(String? surahToMarkIndex) =>
      super.noSuchMethod(
        Invocation.method(
          #showAlertAboutSurasMarking,
          [surahToMarkIndex],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [LocaleProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocaleProvider extends _i1.Mock implements _i6.LocaleProvider {
  @override
  String get currentLocale => (super.noSuchMethod(
        Invocation.getter(#currentLocale),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#currentLocale),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.getter(#currentLocale),
        ),
      ) as String);

  @override
  String get oldLocale => (super.noSuchMethod(
        Invocation.getter(#oldLocale),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#oldLocale),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.getter(#oldLocale),
        ),
      ) as String);

  @override
  _i2.SharedPreferences get sharedPreferences => (super.noSuchMethod(
        Invocation.getter(#sharedPreferences),
        returnValue: _FakeSharedPreferences_0(
          this,
          Invocation.getter(#sharedPreferences),
        ),
        returnValueForMissingStub: _FakeSharedPreferences_0(
          this,
          Invocation.getter(#sharedPreferences),
        ),
      ) as _i2.SharedPreferences);

  @override
  set currentLocale(String? _currentLocale) => super.noSuchMethod(
        Invocation.setter(
          #currentLocale,
          _currentLocale,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set oldLocale(String? _oldLocale) => super.noSuchMethod(
        Invocation.setter(
          #oldLocale,
          _oldLocale,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void saveLocal(String? localeToSave) => super.noSuchMethod(
        Invocation.method(
          #saveLocal,
          [localeToSave],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void changeLocale(String? newLocale) => super.noSuchMethod(
        Invocation.method(
          #changeLocale,
          [newLocale],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isArabicChosen() => (super.noSuchMethod(
        Invocation.method(
          #isArabicChosen,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool didLocaleChange() => (super.noSuchMethod(
        Invocation.method(
          #didLocaleChange,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
